# Generated by Django 5.2.2 on 2025-06-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
