# Generated by Django 5.2.2 on 2025-06-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_delete_certificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoCategory',
            new_name='PhotoCategorie',
        ),
    ]
